version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpass
      - DB_NAME=lubricentro
      - JWT_SECRET=claveultrasecreta
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=lubricentro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "--user=root", "--password=rootpass", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
